# Generated by Django 4.2.3 on 2025-11-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=100)),
                ('C_description', models.TextField()),
                ('C_syllabus', models.TextField()),
                ('C_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('C_image', models.ImageField(upload_to='course_images/')),
            ],
        ),
    ]
